Repository acm-uic/IaC, pull requests merged in 2023-11, with the labels that each got.

#59 Feature/docker ingress
  kubernetes/argocd/stacks/common/docker-ingress.yml
  kubernetes/argocd/stacks/common/traefik.yml
Labels: :boat: Helm, :wheel_of_dharma: k8s

#60 Feature/Marketplace
  kubernetes/argocd/stacks/common/marketplace.yml
  kubernetes/argocd/stacks/common/projects.yml
  kubernetes/argocd/stacks/marketplace/marketplace.yml
  kubernetes/argocd/stacks/marketplace/values.yml
Labels: :sparkles: enhancement, :boat: Helm, :wheel_of_dharma: k8s

#65 Use AAD federated auth for azure login
  .github/workflows/azure_terraform_apply.yml
  .github/workflows/azure_terraform_plan.yml
  azure/README.md
Labels: :cloud: Azure, :sparkles: enhancement, :building_construction: Terraform, :construction: Actions

#76 💽 Installing the Vault Secrets Operator
  kubernetes/argocd/stacks/common/vault-secrets-operator.yml
  kubernetes/argocd/stacks/vault-secrets-operator/values.yml
  kubernetes/argocd/stacks/vault-secrets-operator/vault-secrets-operator.yml
Labels: :sparkles: enhancement, :wheel_of_dharma: k8s

#77 🙈 Adding source repo to infra project
  kubernetes/argocd/stacks/common/projects.yml
Labels: :bug: bug, :wheel_of_dharma: k8s

#78 🔨 Fixing values.yml to reflect vault-secrets-operator values schema
  kubernetes/argocd/stacks/vault-secrets-operator/values.yml
Labels: :bug: bug, :boat: Helm, :wheel_of_dharma: k8s

#79 ⛏️ Fixing address protocol
  kubernetes/argocd/stacks/vault-secrets-operator/values.yml
Labels: :bug: bug, :wheel_of_dharma: k8s

#80 🪄 Adding vault secrets operator role
  kubernetes/argocd/stacks/vault-secrets-operator/values.yml
Labels: :bug: bug, :boat: Helm, :wheel_of_dharma: k8s
