Repository acm-uic/IaC, pull requests merged in 2023-08, with the labels that each got.

#51 🔍 Add kube linter for PRs.
  .github/workflows/kubelint.yml
Labels: :construction: Actions

#49 ⬆️ Feature/ArgoCD-upgrade-2.7.9: Upgrading ArgoCD to 2.7.9
  kubernetes/terraform/stacks/1_k8s_cluster_setup/argocd.tf
  kubernetes/terraform/stacks/1_k8s_cluster_setup/configurations/acmapp_prod.tfvars
Labels: :sparkles: enhancement, :boat: Helm, :wheel_of_dharma: k8s, :building_construction: Terraform

#52 Bug/cert-manager sync
  kubernetes/argocd/stacks/cert-manager/cert-issuers.yml
  kubernetes/argocd/stacks/cert-manager/cert-manager.crds.yaml
  kubernetes/argocd/stacks/cert-manager/self-ca.yml
  kubernetes/argocd/stacks/common/cert-manager.yml
Labels: :bug: bug, :boat: Helm, :wheel_of_dharma: k8s

#55 🔒Feature/vault certs
  kubernetes/argocd/stacks/common/vault-values-override.yml
  kubernetes/argocd/stacks/common/vault.yml
Labels: :sparkles: enhancement, :wheel_of_dharma: k8s

#54 🪲Bug/cert manager sync
  kubernetes/argocd/stacks/cert-manager/self-ca.yml
Labels: :wheel_of_dharma: k8s

#53 ⬆️ Feature/ArgoCD-upgrade-2.8.0: Upgrading ArgoCD to 2.8.0
  kubernetes/terraform/stacks/1_k8s_cluster_setup/configurations/acmapp_prod.tfvars
Labels: :boat: Helm, :wheel_of_dharma: k8s, :building_construction: Terraform

#56 💉 Feature/Azure-Vault-injector
  azure/terraform/stacks/vault-injector/.terraform.lock.hcl
  azure/terraform/stacks/vault-injector/README.md
  azure/terraform/stacks/vault-injector/backend.tf
  azure/terraform/stacks/vault-injector/external_dns.tf
  azure/terraform/stacks/vault-injector/main.tf
  azure/terraform/stacks/vault-injector/providers.tf
Labels: :cloud: Azure, :wheel_of_dharma: k8s, :building_construction: Terraform
